version: "3.8"

networks:
  mynetwork:
    driver: bridge

services:
  knight.ui.web:
    restart: unless-stopped
    build:
      context: ./Knight.UI
    ports:
      - "8080:8080"
    entrypoint: ["npm", "run", "serve"]

  knight.api.web:
    image: knightwebapi
    container_name: knight.api.web
    build:
      context: .
      dockerfile: Knight.API/Dockerfile
    depends_on:
      - mongo
    networks:
      - mynetwork
    
  mongo:
    image: mongo
    restart: always
    ports:
     - 27017:27017
    networks:
      - mynetwork
    volumes:
      - dbdata6:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    networks:
      - mynetwork

volumes:
  dbdata6: