version: "3.8"

networks:
  mynetwork:
    driver: bridge

services:
  mongo:
    image: mongo
    restart: always
    ports:
     - 27017:27017
    networks:
      - mynetwork
    volumes:
      - dbdata6:/data/db

  knight.api.web:
    image: knightwebapi
    container_name: knight.api.web
    build:
      context: .
      dockerfile: Knight.API/Dockerfile
    depends_on:
      - mongo
    ports:
      - "5100:8080"
    networks:
      - mynetwork

  knight.ui.web:
    image: knightuiweb
    container_name: knight.ui.web
    build:
      context: ./Knight.UI
    ports:
      - "8080:8080"
    volumes:
      - ./Knight.UI:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - mynetwork

  knight.reverse.proxy:
    image: knight.reverse.proxy
    container_name: knight.reverse.proxy
    build:
      context: .
      dockerfile: Knight.Infra/NGINX/Dockerfile
    ports:
      - "10000:80"
    depends_on:
      - "knight.api.web"
      - "knight.ui.web"
    networks:
      - mynetwork
      
volumes:
  dbdata6: